on: [push, pull_request]

env:
  JDT: builtin
  ECLIPSE_TAR: ${{ github.workspace }}/../eclipse.tar.gz
  ECLIPSE_EXE: ${{ github.workspace }}/../eclipse/eclipse

jobs:
  gate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]
    name: Python ${{ matrix.python-version }} gate
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: actions/setup-java@v1
        with:
            java-version: 17
      - name: Style dependencies
        run: |
          cat common.json |
            jq -r '.pip | to_entries[] | .key + .value' |
            xargs pip install
      - run: pylint --version
      - name: Download and set up Eclipse dependency
        run: |
          ECLIPSE_ORG_VERSION=$(cat common.json | jq -r '.eclipse.short_version')
          ECLIPSE_ORG_TIMESTAMP=$(cat common.json | jq -r '.eclipse.timestamp')
          wget --no-verbose https://archive.eclipse.org/eclipse/downloads/drops4/R-${ECLIPSE_ORG_VERSION}-${ECLIPSE_ORG_TIMESTAMP}/eclipse-SDK-${ECLIPSE_ORG_VERSION}-linux-gtk-x86_64.tar.gz -O $ECLIPSE_TAR
          tar -C ${{ github.workspace }}/.. -xf $ECLIPSE_TAR
      - name: mx gate
        run: ./mx --strict-compliance gate --strict-mode
      - name: Test native build without vcs dir
        run: |
          rm -rf .git
          ./mx -V build --projects com.oracle.jvmtiasmagent
